name: Build

on:
  push:
  pull_request:
    branches:
      - main

# ros 2 ci: https://github.com/marketplace/actions/ros-2-ci-action
# doc: https://ubuntu.com/blog/ros-2-ci-with-github-actions
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.2.2
        with:
          required-ros-distributions: galactic

      - name: ROS 2 CI Action
        uses: ros-tooling/action-ros-ci@0.2.4
        with:
          package-name: lbr_fri_ros2_stack
          target-ros2-distro: galactic
          vcs-repo-file-url: https://raw.githubusercontent.com/KCL-BMEIS/lbr_fri_ros2_stack/main/lbr_fri_ros2_stack/repos.yml

      - name: Upload Logs
        uses: actions/upload-artifact@v2.3.1
        with:
          name: colcon-logs
          path: ros_ws/log
        if: always()
